SELECT 'FoundInSAP' as STATUS, CORE_ORDER.SUB_ORD_REF_NUM, SAP_ORDER.SUB_ORD_REF_NUM AS SAP_EIS_ORDNUM, CORE_ORDER.PURCHASE_ORDER_DATE, CORE_ORDER.ORDER_PRICE, CORE_ORDER.STATUS AS CORE_STATUS,    SAP_ORDER.STATUS_CODE, SAP_ORDER.STATUS_MSG  FROM (
SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  CORE_REQUEST_DATE, SOURCE_SYSTEM, STATUS,
RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK2 
FROM RECON_CORE_PDMS_ORDER_TXN WHERE CORE_REQUEST_DATE >= startDate and CORE_REQUEST_DATE <= endDate) WHERE  RANK2 =1) CORE_ORDER
JOIN(
SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  SAP_CREATED_DATE, STATUS_CODE, STATUS_MSG, 
RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_SAP_PDMS_ORDER_TXN
WHERE SAP_CREATED_DATE >= startDate and SAP_CREATED_DATE <= endDate) WHERE RANK3=1) SAP_ORDER
ON CORE_ORDER.SUB_ORD_REF_NUM = SAP_ORDER.SUB_ORD_REF_NUM
UNION
SELECT 'MissingInSAP' as STATUS, CORE_SAP_FINAL.SUB_ORD_REF_NUM, EIS_ORDER.SUB_ORD_REF_NUM,            CORE_SAP_FINAL.PURCHASE_ORDER_DATE, CORE_SAP_FINAL.ORDER_PRICE, CORE_SAP_FINAL.CORE_STATUS AS CORE_STATUS, null, EIS_ORDER.STATUS AS ST_MSG  FROM (
SELECT * FROM (
SELECT  CORE_ORDER.SUB_ORD_REF_NUM, SAP_ORDER.SUB_ORD_REF_NUM as SAP_ORD_NUM, CORE_ORDER.PURCHASE_ORDER_DATE, CORE_ORDER.ORDER_PRICE, CORE_ORDER.STATUS AS CORE_STATUS, SAP_ORDER.STATUS_CODE, SAP_ORDER.STATUS_MSG  FROM (
SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  CORE_REQUEST_DATE, SOURCE_SYSTEM, STATUS,
RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK2 
FROM RECON_CORE_PDMS_ORDER_TXN WHERE CORE_REQUEST_DATE >= startDate and CORE_REQUEST_DATE <= endDate) WHERE  RANK2 =1) CORE_ORDER
LEFT OUTER JOIN(
SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  SAP_CREATED_DATE, STATUS_CODE, STATUS_MSG, 
RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_SAP_PDMS_ORDER_TXN
WHERE SAP_CREATED_DATE >= startDate and SAP_CREATED_DATE <= endDate) WHERE RANK3=1) SAP_ORDER
ON CORE_ORDER.SUB_ORD_REF_NUM = SAP_ORDER.SUB_ORD_REF_NUM 
) CORE_SAP WHERE CORE_SAP.SAP_ORD_NUM is null )CORE_SAP_FINAL 
LEFT OUTER JOIN(SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  TIBCO_CREATE_DATE, STATUS,  
RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_EIS_PDMS_ORDER_TXN
WHERE TIBCO_CREATE_DATE >= startDate and TIBCO_CREATE_DATE <= endDate) WHERE RANK3=1) EIS_ORDER
ON EIS_ORDER.SUB_ORD_REF_NUM= CORE_SAP_FINAL.SUB_ORD_REF_NUM


CREATE OR REPLACE PACKAGE recon_pdms_order_pkg  AS 
  PROCEDURE recon_pdms_order_errors (
  startDate IN  Timestamp,
  endDate IN Timestamp,
  errcode IN Varchar2,
  c_results OUT SYS_REFCURSOR
  ); 
END recon_pdms_order_pkg;

CREATE OR REPLACE PACKAGE BODY recon_pdms_order_pkg AS
  PROCEDURE recon_pdms_order_errors (
      startDate IN  Timestamp,
      endDate IN Timestamp,
      errcode IN Varchar2,
      c_results OUT SYS_REFCURSOR
      )
  AS
    log varchar2(1000);
    user_name varchar2(20);
    filterCondn varchar2(100);
    
    BEGIN
    user_name := 'Admin';
    log := 'Begin PDMS Orders Fetch errors ' || startDate || ' ' || endDate || ' ' || errcode;
    INSERT INTO svc_logs( APPLICATION,LOG_LEVEL, LOG_LINE, log_text, create_user, create_date) VALUES ('recon_pdms_order_errors', 'INFO', '1.1', log, user_name, sysdate);
    
    IF errcode = 'SAP' THEN
          filterCondn:= ' WHERE STATUS=''FoundInSAP'' and STATUS_CODE !=53';
    ELSIF errcode = 'EIS' THEN
        filterCondn:= ' WHERE STATUS=''MissingInSAP'' and SAP_EIS_ORDNUM is not null';
    ELSIF errcode = 'SRC' THEN
        filterCondn:= ' WHERE STATUS=''MissingInSAP'' and SAP_EIS_ORDNUM is null';
    ELSE
        filterCondn:= ' WHERE 1!=1';
    END IF;
    
    INSERT INTO svc_logs( APPLICATION,LOG_LEVEL, LOG_LINE, log_text, create_user, create_date) VALUES ('recon_pdms_order_errors', 'INFO', '1.2', filterCondn, user_name, sysdate);
    
       OPEN c_results FOR 'SELECT STATUS, SUB_ORD_REF_NUM, STATUS_CODE,  ORDER_PRICE, SAP_EIS_ORDNUM, CORE_REQUEST_DATE, STATUS_MSG FROM(
        SELECT ''FoundInSAP'' as STATUS, CORE_ORDER.SUB_ORD_REF_NUM, SAP_ORDER.SUB_ORD_REF_NUM AS SAP_EIS_ORDNUM, CORE_ORDER.CORE_REQUEST_DATE, CORE_ORDER.ORDER_PRICE, CORE_ORDER.STATUS AS CORE_STATUS,    SAP_ORDER.STATUS_CODE, SAP_ORDER.STATUS_MSG  FROM (
        SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  CORE_REQUEST_DATE, SOURCE_SYSTEM, STATUS,
        RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK2 
        FROM RECON_CORE_PDMS_ORDER_TXN WHERE CORE_REQUEST_DATE >= '''||startDate||''' and CORE_REQUEST_DATE <= '''||endDate||''') WHERE  RANK2 =1) CORE_ORDER
        JOIN(
        SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  SAP_CREATED_DATE, STATUS_CODE, STATUS_MSG, 
        RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_SAP_PDMS_ORDER_TXN
        WHERE SAP_CREATED_DATE >= '''||startDate||''' and SAP_CREATED_DATE <= '''||endDate||''') WHERE RANK3=1) SAP_ORDER
        ON CORE_ORDER.SUB_ORD_REF_NUM = SAP_ORDER.SUB_ORD_REF_NUM
        UNION
        SELECT ''MissingInSAP'' as STATUS, CORE_SAP_FINAL.SUB_ORD_REF_NUM, EIS_ORDER.SUB_ORD_REF_NUM,            CORE_SAP_FINAL.CORE_REQUEST_DATE, CORE_SAP_FINAL.ORDER_PRICE, CORE_SAP_FINAL.CORE_STATUS AS CORE_STATUS, null, EIS_ORDER.STATUS AS ST_MSG  FROM (
        SELECT * FROM (
        SELECT  CORE_ORDER.SUB_ORD_REF_NUM, SAP_ORDER.SUB_ORD_REF_NUM as SAP_ORD_NUM, CORE_ORDER.CORE_REQUEST_DATE, CORE_ORDER.ORDER_PRICE, CORE_ORDER.STATUS AS CORE_STATUS, SAP_ORDER.STATUS_CODE, SAP_ORDER.STATUS_MSG  FROM (
        SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  CORE_REQUEST_DATE, SOURCE_SYSTEM, STATUS,
        RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK2 
        FROM RECON_CORE_PDMS_ORDER_TXN WHERE CORE_REQUEST_DATE >= '''||startDate||''' and CORE_REQUEST_DATE <= '''||endDate||''') WHERE  RANK2 =1) CORE_ORDER
        LEFT OUTER JOIN(
        SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  SAP_CREATED_DATE, STATUS_CODE, STATUS_MSG, 
        RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_SAP_PDMS_ORDER_TXN
        WHERE SAP_CREATED_DATE >= '''||startDate||''' and SAP_CREATED_DATE <= '''||endDate||''') WHERE RANK3=1) SAP_ORDER
        ON CORE_ORDER.SUB_ORD_REF_NUM = SAP_ORDER.SUB_ORD_REF_NUM 
        ) CORE_SAP WHERE CORE_SAP.SAP_ORD_NUM is null )CORE_SAP_FINAL 
        LEFT OUTER JOIN(
        SELECT * FROM (SELECT ID, SUB_ORD_REF_NUM, PURCHASE_ORDER_DATE, ORDER_PRICE,  TIBCO_CREATE_DATE, STATUS,  
        RANK()  OVER(PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS RANK3 FROM RECON_EIS_PDMS_ORDER_TXN
        WHERE TIBCO_CREATE_DATE >= '''||startDate||''' and TIBCO_CREATE_DATE <= '''||endDate||''') WHERE RANK3=1) EIS_ORDER
        ON EIS_ORDER.SUB_ORD_REF_NUM= CORE_SAP_FINAL.SUB_ORD_REF_NUM)' || filterCondn ;

    END recon_pdms_order_errors;
END recon_pdms_order_pkg;

--select * from svc_logs order by log_id desc;
var results refcursor;
exec recon_pdms_order_pkg.recon_pdms_order_errors( TO_TIMESTAMP ('2017/06/01 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), TO_TIMESTAMP ('2017/06/06 23:59:59', 'YYYY/MM/DD HH24:MI:SS'), 'SRC', :results);
print results
--COMMIT
  