CREATE OR REPLACE PACKAGE recon_order_pkg  AS
  PROCEDURE recon_order_errors (
    startDate IN  Timestamp,
    endDate IN Timestamp,
    errcode IN Varchar2,
    srcSystem IN Varchar2,
    currencyCode IN Varchar2,
    c_results OUT SYS_REFCURSOR
  );
END recon_order_pkg;

CREATE OR REPLACE PACKAGE BODY recon_order_pkg AS
  PROCEDURE recon_order_errors (
    startDate IN  Timestamp,
    endDate IN Timestamp,
    errcode IN Varchar2,
    srcSystem IN Varchar2,
    currencyCode IN Varchar2,
    c_results OUT SYS_REFCURSOR
  )
  AS
    log varchar2(1000);
    user_name varchar2(20);
    filterCondn varchar2(200);

    BEGIN
      user_name := 'Admin';
      log := 'Begin Orders Fetch errors ' || startDate || ' ' || endDate || ' ' || errcode;
      INSERT INTO svc_logs( APPLICATION,LOG_LEVEL, LOG_LINE, log_text, create_user, create_date) VALUES ('recon_order_errors', 'INFO', '1.1', log, user_name, sysdate);

      IF errcode = 'SAP' THEN
        filterCondn:= ' WHERE STATUS_FOUND=''FoundInSAP'' and STATUS != ''SUCCESS''';
      ELSIF errcode = 'EIS' THEN
        filterCondn:= ' WHERE STATUS_FOUND=''MissingInSAP'' and SAP_EIS_ORDER is not null';
      ELSIF errcode = 'SRC' THEN
        filterCondn:= ' WHERE STATUS_FOUND=''MissingInSAP'' and SAP_EIS_ORDER is null';
      ELSE
        filterCondn:= ' WHERE 1!=1';
      END IF;

      IF UPPER(currencyCode) != 'ALL' THEN
        filterCondn:= filterCondn || ' and CURRENCY_CODE ='''||currencyCode||'''';
      END IF;

      filterCondn:= filterCondn || ' and SOURCE_SYSTEM = '''||srcSystem||'''';

      INSERT INTO svc_logs( APPLICATION,LOG_LEVEL, LOG_LINE, log_text, create_user, create_date) VALUES ('recon_order_errors', 'INFO', '1.2', filterCondn, user_name, sysdate);

      OPEN c_results FOR 'SELECT STATUS_FOUND, SUB_ORD_REF_NUM, SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE,  SAP_EIS_ORDER, CORE_LOAD_DATE_TIME, STATUS, STATUS_CODE, STATUS_MSG FROM (
    SELECT ''FoundInSAP'' AS STATUS_FOUND, CORE_ORDER.SUB_ORD_REF_NUM, TRIM(CORE_ORDER.SOURCE_SYSTEM) AS SOURCE_SYSTEM, CORE_ORDER.CURRENCY_CODE, CORE_ORDER.TOTAL_PRICE,
SAP_ORDER.SUB_ORD_REF_NUM AS SAP_EIS_ORDER, CORE_LOAD_DATE_TIME, STATUS, STATUS_CODE, STATUS_MSG  FROM (
SELECT SUB_ORD_REF_NUM, SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE, CORE_LOAD_DATE_TIME, ORDER_TS FROM (
SELECT RECON_CORE_ORDER_TXN.*, RANK() OVER (PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS CORE_RNK FROM RECON_CORE_ORDER_TXN
WHERE CORE_LOAD_DATE_TIME>= '''||startDate||''' and CORE_LOAD_DATE_TIME <= '''||endDate||''') WHERE CORE_RNK =1) CORE_ORDER
JOIN (
SELECT SUB_ORD_REF_NUM,  SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE, SAP_CREATED_DATE, STATUS, STATUS_CODE, STATUS_MSG FROM (
SELECT RECON_SAP_ORDER_TXN.*, RANK() OVER (PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS SAP_RNK  FROM RECON_SAP_ORDER_TXN
WHERE SAP_CREATED_DATE>= '''||startDate||''' and SAP_CREATED_DATE <= '''||endDate||''') WHERE SAP_RNK =1
) SAP_ORDER
ON SAP_ORDER.SUB_ORD_REF_NUM = CORE_ORDER.SUB_ORD_REF_NUM
UNION
SELECT ''MissingInSAP'' AS STATUS_FOUND, CORE_SAP.SUB_ORD_REF_NUM, TRIM(CORE_SAP.SOURCE_SYSTEM), CORE_SAP.CURRENCY_CODE, CORE_SAP.TOTAL_PRICE,
EIS_ORDER.SUB_ORD_REF_NUM, CORE_LOAD_DATE_TIME, EIS_ORDER.STATUS, EIS_ORDER.STATUS_CODE, EIS_ORDER.STATUS_MSG  FROM (
SELECT  CORE_ORDER.SUB_ORD_REF_NUM, CORE_ORDER.SOURCE_SYSTEM, CORE_ORDER.CURRENCY_CODE, CORE_ORDER.TOTAL_PRICE, CORE_LOAD_DATE_TIME, STATUS_CODE, STATUS_MSG  FROM (
SELECT SUB_ORD_REF_NUM, SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE, CORE_LOAD_DATE_TIME, ORDER_TS FROM (
SELECT RECON_CORE_ORDER_TXN.*, RANK() OVER (PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS CORE_RNK FROM RECON_CORE_ORDER_TXN
WHERE CORE_LOAD_DATE_TIME>= '''||startDate||''' and CORE_LOAD_DATE_TIME <= '''||endDate||''') WHERE CORE_RNK =1) CORE_ORDER
LEFT JOIN (
SELECT SUB_ORD_REF_NUM,  SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE, SAP_CREATED_DATE,STATUS, STATUS_CODE, STATUS_MSG FROM (
SELECT RECON_SAP_ORDER_TXN.*, RANK() OVER (PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS SAP_RNK  FROM RECON_SAP_ORDER_TXN
WHERE SAP_CREATED_DATE>= '''||startDate||''' and SAP_CREATED_DATE <= '''||endDate||''') WHERE SAP_RNK =1
) SAP_ORDER
ON SAP_ORDER.SUB_ORD_REF_NUM = CORE_ORDER.SUB_ORD_REF_NUM
WHERE SAP_ORDER.SUB_ORD_REF_NUM IS NULL) CORE_SAP
LEFT JOIN(
SELECT SUB_ORD_REF_NUM,  SOURCE_SYSTEM, CURRENCY_CODE, TOTAL_PRICE, TIBCO_CREATED_DATE,STATUS, STATUS_CODE, STATUS_MSG FROM(
SELECT RECON_EIS_ORDER_TXN.*, RANK() OVER (PARTITION BY SUB_ORD_REF_NUM ORDER BY ID DESC ) AS EIS_RNK FROM RECON_EIS_ORDER_TXN
WHERE TIBCO_CREATED_DATE>= '''||startDate||''' and TIBCO_CREATED_DATE <= '''||endDate||''') WHERE EIS_RNK =1
)EIS_ORDER
ON CORE_SAP.SUB_ORD_REF_NUM = EIS_ORDER.SUB_ORD_REF_NUM)' || filterCondn ;

    END recon_order_errors;
END recon_order_pkg;

--select * from svc_logs order by log_id desc;
--var results refcursor;
--exec recon_order_pkg.recon_order_errors( TO_TIMESTAMP ('2017/06/21 00:00:00', 'YYYY/MM/DD HH24:MI:SS'), TO_TIMESTAMP ('2017/06/23 23:59:59', 'YYYY/MM/DD HH24:MI:SS'), 'EIS', 'CSS', 'ALL',:results);
--print results
--COMMIT